@api = http://localHost:3000/tasks

GET {{api}}

###

GET {{api}}/3

###

GET {{api}}/count

###

POST {{api}}
content-type: application/json

{
"title":"prueba 4",
"description":"yo probando un post"
}

# tener cuidado de no dejar espacios y q el content type es en minuscula

###
DELETE {{api}}/1

###
PUT {{api}}/2
content-type: application/json

{
  "title":"tarea 2 de nuevo"
}